#!/bin/bash
#
#Script to coarse-grain and run energy minimization


export PATH="/lindorffgrp-isilon/thomasen/software/miniconda3/bin:$PATH"
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/lindorffgrp-isilon/wyong/software/openmpi401/lib

gmx=/lindorffgrp-isilon/wyong/software/GMX20194/bin/gmx_mpi
python=/lindorffgrp-isilon/thomasen/software/miniconda3/bin/python3.7

martinize=/lindorffgrp-isilon/thomasen/software/miniconda3/bin/martinize2

wget http://cgmartini.nl/images/tools/insane/insane.py
insane=insane.py

minmdp=minimization.mdp
FF=martini3001
ffdir=/storage1/skaalum/software/force-fields/Martini/martini_v300_modified_protein_ff
dssp=/lindorffgrp-isilon/thomasen/software/miniconda3/bin/mkdssp

cpbnm=/storage1/skaalum/software/python_modules_and_scripts/Changing_protein_beadtype_names_in_the_molecule_0_itp_file_v1.py

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
#export GMX_MAXCONSTRWARN=-1

#Loop through proteins
for i in TIA1 hnRNPA1 hSUMO_hnRNPA1 THB_C2 Ubq2 Ubq3 Ubq4 Gal-3 mTurq_GS0_mNeon mTurq_GS8_mNeon mTurq_GS16_mNeon mTurq_GS24_mNeon mTurq_GS32_mNeon mTurq_GS48_mNeon C5_C6_C7
do

if [[ "$i" == "TIA1" ]]
then
	salt=0.1
	box=15.9
	ss=CCTTSCSEEEEESCCTTSCHHHHHHHHHHHSCEEEEEEECCSSSCCCEEEEEESCHHHHHHHHHHHTTCEETTEECEEEEECCCCSSCCCCCSSCEEEEEESCCTTCCHHHHHHHHTTTSCEEEEEEEECTTTCCEEEEEEEEESSHHHHHHHHHHHTTCEETTEECEEEESSCSSCCCCCCSCSSCCSTTHHHHHTCCCTTCCEEEEECCCSSCCHHHHHHHHTTTSCEEEEEEETTTTEEEEEESSHHHHHHHHHHHTTCEETTEECEEEECC
fi

if [[ "$i" == "hnRNPA1" ]]
then
	salt=0.15
	box=25.6
	ss=CCSSSCCCCCSSSSEEEEESCCTTCCHHHHHHHHTSSSCEEEEEEEEETTTTEEEEEEEEEESSHHHHHHHHHHCSCEETTEECEEEECCSSSCSSSSCCCCCCSBEEEECCCTTCCHHHHHHHHTTTCCCSEEEEEECSSSCCEEEEEEEECSCHHHHHHHHHCSCEEETTEEEEEEECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
fi

if [[ "$i" == "hSUMO_hnRNPA1" ]]
then
	salt=0.1
	box=28.4
	ss=CCCCCCCCCCCCCCCCCCCCCSSSSSTTCCCCCSSSSSCCCSSCEEEBCCSSSCCCCEECCCSSCTTTHHHHHHHHTCCTTTTEECCSSSSCCCTTCCSSSCCCSSCCBCCCEECCCCCSSSSSCCCCCSSSSEEEEESCCTTCCHHHHHHHHTSSSCEEEEEEEEETTTTEEEEEEEEEESSHHHHHHHHHHCSCEETTEECEEEECCSSSCSSSSCCCCCCSBEEEECCCTTCCHHHHHHHHTTTCCCSEEEEEECSSSCCEEEEEEEECSCHHHHHHHHHCSCEEETTEEEEEEECCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC
fi

if [[ "$i" == "THB_C2" ]]
then
	salt=0.15
	box=15.0
	ss=GCGSECCCEICCCCCCSECECICCCCGCTCCCGCCCCCCGCCCCCCCSTCCCCCCECCCCCSCGHCICCTCECCCHCCECCCCCCGCEICCSGSCCICESIGCCCTCTISCCSCCCCCCCCCCCGGECCSTECCCCE
fi

if [[ "$i" == "Ubq2" ]]
then
	salt=0.33
	box=16.8
	ss=CCSCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCC
fi

if [[ "$i" == "Ubq3" ]]
then
	salt=0.33
	box=17.3
	ss=CCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCC
fi

if [[ "$i" == "Ubq4" ]]
then
	salt=0.33
	box=18.0
	ss=CCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCCCCICCCTCTGCTITCECECSCTIECCCCCICCCEGICCCCCCCICCGCCCECGCTCSCCCICCESTCHCCCCCCCC

fi

if [[ "$i" == "Gal-3" ]]
then
	salt=0.04
	box=23.5
	ss=CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCGGCCCCCCITICGTCCCCCCCICCCCCCGCCCCCHCCCCCCECCCCCICCCTCCCCCCGCEECCSCCCCESGCCCCICCCCECCHCCCCCCCCHCCCCCHCCCCCCEISCCGISGCICCTSCSCTCI
fi

if [[ "$i" == "C5_C6_C7" ]]
then
	salt=0.28
	box=20.6
	ss=CCCSCCCCCCIHCCCCGCICCTICCCCGCCCCCCCCISGCCCCTCICCCCITCCCCCCCCCCCCCCCCTCCSCCCCCCCCCCCCTCCCCCCETTCCCSICTCEGCECECEGCCTCTCCCCCGECCCCCTCCCICCCCCCCCCCISCCGECSCTCCCECCCCCGGCCICGCICECCCCCSCCCCCCCCCCICECSHECCCCIEGCCCECCCCCCCCCCCSCCSCCSCCCCCCCCCSECTHCCCECCSCTTCSCCCCCCECCGCGGCCGCSCECCCEGCSECCCCCCGCTEHTSICCCCCCTGCCCCCCCCCHCCCGCGCCCTTTECCTC
fi

if [[ "$i" == "mTurq_GS0_mNeon" ]]
then
	salt=0.15
	box=21.9
	ss=SCGEECCTGCCCICCECCGCCCGHCCSCSGEGEGCCTCGCCTCCCICTTGCCCCCCCTCCTTCSCGCCCCCCCCCHCCCHCCCCSCCCEGCCCECTICCCCCGCCCTCCECCCEGCTCCCCIECCGICCCECGCICGHCCECCCCSCCCCITCCCCCCGICCCCCICHCIECGGCCCCCHCCCCTCIGCGCCCCCCCHCCSTCSCCSCCCCECCCHCCCCECCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTHECHICGSICGCCCCCCGCGTGCCCCGCEECCCCSTCGCCCCSCCICCCHIGCGCHCCCCCCCGCSCCCCCCCCGSGCCCHCTCCCECGCSCTCCCCCTCEGSHICGECCCCGTGCCCCGCCCTCSCTCCCCCCSCCTCCCCCTIISTCCCSCTTGCGCCCCSTCCTTCTCCCCCCCCCCCCCCCCCCCCTECCHSCTECCCCECCCCCTC
fi

if [[ "$i" == "mTurq_GS8_mNeon" ]]
then
	salt=0.15
	box=22.1
	ss=SCGEECCTGCCCICCECCGCCCGHCCSCSGEGEGCCTCGCCTCCCICTTGCCCCCCCTCCTTCSCGCCCCCCCCCHCCCHCCCCSCCCEGCCCECTICCCCCGCCCTCCECCCEGCTCCCCIECCGICCCECGCICGHCCECCCCSCCCCITCCCCCCGICCCCCICHCIECGGCCCCCHCCCCTCIGCGCCCCCCCHCCSTCSCCSCCCCECCCHCCCCECCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTHECHICGSICGCCCCCCGCGTGCCCCGCEECCCCSTCGCCCCSCCICCCHIGCGCHCCCCCCCGCSCCCCCCCCGSGCCCHCTCCCECGCSCTCCCCCTCEGSHICGECCCCGTGCCCCGCCCTCSCTCCCCCCSCCTCCCCCTIISTCCCSCTTGCGCCCCSTCCTTCTCCCCCCCCCCCCCCCCCCCCTECCHSCTECCCCECCCCCTC
fi

if [[ "$i" == "mTurq_GS16_mNeon" ]]
then
	salt=0.15
	box=22.2
	ss=SCGEECCTGCCCICCECCGCCCGHCCSCSGEGEGCCTCGCCTCCCICTTGCCCCCCCTCCTTCSCGCCCCCCCCCHCCCHCCCCSCCCEGCCCECTICCCCCGCCCTCCECCCEGCTCCCCIECCGICCCECGCICGHCCECCCCSCCCCITCCCCCCGICCCCCICHCIECGGCCCCCHCCCCTCIGCGCCCCCCCHCCSTCSCCSCCCCECCCHCCCCECCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTHECHICGSICGCCCCCCGCGTGCCCCGCEECCCCSTCGCCCCSCCICCCHIGCGCHCCCCCCCGCSCCCCCCCCGSGCCCHCTCCCECGCSCTCCCCCTCEGSHICGECCCCGTGCCCCGCCCTCSCTCCCCCCSCCTCCCCCTIISTCCCSCTTGCGCCCCSTCCTTCTCCCCCCCCCCCCCCCCCCCCTECCHSCTECCCCECCCCCTC
fi

if [[ "$i" == "mTurq_GS24_mNeon" ]]
then
	salt=0.15
	box=22.4
	ss=SCGEECCTGCCCICCECCGCCCGHCCSCSGEGEGCCTCGCCTCCCICTTGCCCCCCCTCCTTCSCGCCCCCCCCCHCCCHCCCCSCCCEGCCCECTICCCCCGCCCTCCECCCEGCTCCCCIECCGICCCECGCICGHCCECCCCSCCCCITCCCCCCGICCCCCICHCIECGGCCCCCHCCCCTCIGCGCCCCCCCHCCSTCSCCSCCCCECCCHCCCCECCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTHECHICGSICGCCCCCCGCGTGCCCCGCEECCCCSTCGCCCCSCCICCCHIGCGCHCCCCCCCGCSCCCCCCCCGSGCCCHCTCCCECGCSCTCCCCCTCEGSHICGECCCCGTGCCCCGCCCTCSCTCCCCCCSCCTCCCCCTIISTCCCSCTTGCGCCCCSTCCTTCTCCCCCCCCCCCCCCCCCCCCTECCHSCTECCCCECCCCCTC
fi

if [[ "$i" == "mTurq_GS32_mNeon" ]]
then
	salt=0.15
	box=22.6
	ss=SCGEECCTGCCCICCECCGCCCGHCCSCSGEGEGCCTCGCCTCCCICTTGCCCCCCCTCCTTCSCGCCCCCCCCCHCCCHCCCCSCCCEGCCCECTICCCCCGCCCTCCECCCEGCTCCCCIECCGICCCECGCICGHCCECCCCSCCCCITCCCCCCGICCCCCICHCIECGGCCCCCHCCCCTCIGCGCCCCCCCHCCSTCSCCSCCCCECCCHCCCCECCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTHECHICGSICGCCCCCCGCGTGCCCCGCEECCCCSTCGCCCCSCCICCCHIGCGCHCCCCCCCGCSCCCCCCCCGSGCCCHCTCCCECGCSCTCCCCCTCEGSHICGECCCCGTGCCCCGCCCTCSCTCCCCCCSCCTCCCCCTIISTCCCSCTTGCGCCCCSTCCTTCTCCCCCCCCCCCCCCCCCCCCTECCHSCTECCCCECCCCCTC
fi

if [[ "$i" == "mTurq_GS48_mNeon" ]]
then
	salt=0.15
	box=23.0
	ss=SCGEECCTGCCCICCECCGCCCGHCCSCSGEGEGCCTCGCCTCCCICTTGCCCCCCCTCCTTCSCGCCCCCCCCCHCCCHCCCCSCCCEGCCCECTICCCCCGCCCTCCECCCEGCTCCCCIECCGICCCECGCICGHCCECCCCSCCCCITCCCCCCGICCCCCICHCIECGGCCCCCHCCCCTCIGCGCCCCCCCHCCSTCSCCSCCCCECCCHCCCCECCTCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCTHECHICGSICGCCCCCCGCGTGCCCCGCEECCCCSTCGCCCCSCCICCCHIGCGCHCCCCCCCGCSCCCCCCCCGSGCCCHCTCCCECGCSCTCCCCCTCEGSHICGECCCCGTGCCCCGCCCTCSCTCCCCCCSCCTCCCCCTIISTCCCSCTTGCGCCCCSTCCTTCTCCCCCCCCCCCCCCCCCCCCTECCHSCTECCCCECCCCCTC
fi

echo -e "\n     $i has ${salt}M salt"

#Starting structure and script for choosing rubberbands and scFix-dihedrals
pdb=${i}.pdb
EN_script=choose_rubber_bands.py
scFix_script=choose_scFix_dihedrals.py

#Make directory, cp .pdb, insane.py, and the choosing rubber bands and scFix dihedrals files there and cd there
dir=${i}
cp $insane $dir
cp $EN_script $dir
cp $scFix_script $dir
cd $dir

#Martinize
$python $martinize -f $pdb -o PRO_topol.top -x PRO_CG.pdb -ff $FF -cys auto -elastic -ef 700.0 -el 0.5 -eu 0.9 -ea 0 -ep 0 -scfix -ff-dir $ffdir/martini_v3.0.0_proteins/force_fields/ -map-dir $ffdir/martini_v3.0.0_proteins/mappings/ -ss $ss

#Put protein in box
$gmx editconf -f PRO_CG.pdb -o PRO_CG.gro -bt dodecahedron -box $box <<EOF
1
EOF

#Solvate using insane.py
python2.7 $insane -f PRO_CG.gro -o PRO_SOL_IONS.gro -pbc keep -salt $salt -sol W -center -p PRO_topol_SOL_IONS.top

#The next few blocks modify the toplogy file and molecule_0.itp file:

#Remove #include include martini.itp and substitute ion names in topology file
perl -pi -e's/#include "martini.itp"//g' PRO_topol_SOL_IONS.top
perl -pi -e's/NA\+/NA/g' PRO_topol_SOL_IONS.top
perl -pi -e's/CL-/CL/g' PRO_topol_SOL_IONS.top

#Change beadtype names for BB termini in molecule_0.itp
$python $cpbnm

#Rename molecule_0.itp to PRO.itp and rename "molecule_0" as "Protein" in PRO.itp file
mv molecule_0.itp PRO.itp
perl -pi -e's/molecule_0/Protein/g' PRO.itp

#Add "#include .itp" lines to PRO_topol_SOL_IONS.top
cat <<EOF > others.top
#include "$ffdir/martini_v3.0.0.itp"
#include "PRO.itp"
#include "$ffdir/martini_v3.0.0_ions_v1.itp"
#include "$ffdir/martini_v3.0.0_solvents_v1.itp"
EOF
cat others.top PRO_topol_SOL_IONS.top >a
mv a PRO_topol_SOL_IONS.top

#Run energy minimization
$gmx grompp -f ../$minmdp -p PRO_topol_SOL_IONS.top -c PRO_SOL_IONS.gro -o min.tpr -pp all_PRO.top -maxwarn 3 -r PRO_SOL_IONS.gro
nohup $gmx mdrun -deffnm min -v -ntomp 2 &

$python $EN_script $i
$python $scFix_script $i

if [[ "$i" == "C5_C6_C7" ]]
then

$python ../remove_intrachain_rubberbands_C5_C6_C7.py 
	
fi

rm $insane

cd ..

done

