#!/bin/csh
# Generated by CHARMM-GUI (http://www.charmm-gui.org)
# Minimization
setenv GMX_MAXCONSTRWARN -1
gmx_mpi grompp -f step6.0_minimization.mdp -o step6.0_minimization.tpr -c step5_charmm2gmx.pdb -r step5_charmm2gmx.pdb -p system.top -n index.ndx -maxwarn 1
gmx_mpi mdrun -deffnm step6.0_minimization -ntomp 16 -v

# step6.1
gmx_mpi grompp -f step6.1_minimization.mdp -o step6.1_minimization.tpr -c step6.0_minimization.gro -r step5_charmm2gmx.pdb -p system.top -n index.ndx -maxwarn 1
gmx_mpi mdrun -deffnm step6.1_minimization -ntomp 16 -v
unsetenv GMX_MAXCONSTRWARN

# Equilibration
set cnt    = 2
set cntmax = 6

while ( ${cnt} <= ${cntmax} )
    @ pcnt = ${cnt} - 1
    if ($cnt == 2) then
        gmx_mpi grompp -f step6.${cnt}_equilibration.mdp -o step6.${cnt}_equilibration.tpr -c step6.${pcnt}_minimization.gro -r step5_charmm2gmx.pdb -p system.top -n index.ndx
    else
        gmx_mpi grompp -f step6.${cnt}_equilibration.mdp -o step6.${cnt}_equilibration.tpr -c step6.${pcnt}_equilibration.gro -r step5_charmm2gmx.pdb -p system.top -n index.ndx
    endif
    gmx_mpi mdrun -deffnm step6.${cnt}_equilibration -ntomp 16 -v
    @ cnt += 1
end


